#!/usr/bin/env ruby

#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',

#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',

#   :git => 'https://github.com/findsyou/cookbooks',

#   :ref => 'postgresql-improvements'

cookbook "ntp"

cookbook "php", '>= 1.1.0',

   :git => 'https://github.com/foobugs-cookbooks/php'

cookbook "database"

cookbook "mysql"

cookbook "couchdb"

cookbook "mongodb"

cookbook "nginx"
